//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Hotelv4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Id { get; set; }

        [Required]
        [Display(Name = "Hotel Name")]
        [StringLength(50, ErrorMessage = "The Hotel Name must be less than 50 characters long.")]
        public string Name { get; set; }

        [Required]
        public string Address { get; set; }
        [Required]
        [Display(Name = "Rating")]
        [StringLength(1, ErrorMessage = "The Rating should be within 0 ~ 5")]
        public int Rating { get; set; }

        [Required]
        [Display(Name = "Update Date")]
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }

    internal class Reservations
    {
    }
}
